DROP TABLE IF EXISTS BCH_SENDNOTIFYLOGS;

CREATE TABLE BCH_SENDNOTIFYLOGS
(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  TXID NVARCHAR(64) NOT NULL,
  ADDRESS NVARCHAR(34),
  NOTIFIEDCOUNT INT DEFAULT 0,
  NOTIFYRESPONSETEXT TEXT,
  NEXTNOTIFYTIME DATETIME  DEFAULT CURRENT_TIMESTAMP(),
  CREATETIME DATETIME DEFAULT CURRENT_TIMESTAMP()
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE BCH_SENDNOTIFYLOGS ADD INDEX IX_BCH_SENDNOTIFYLOGS_NEXTNOTIFYTIME(NEXTNOTIFYTIME);
