
DROP TABLE IF EXISTS BCH_SENDTRANSACTIONDETAILS;

CREATE TABLE BCH_SENDTRANSACTIONDETAILS
(
  TXID NVARCHAR(64),
  ADDRESS NVARCHAR(34),
  AMOUNT DECIMAL(16, 8)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE BCH_SENDTRANSACTIONDETAILS ADD PRIMARY KEY PK_BCH_SENDTRANSACTIONDETAILS(TXID, ADDRESS);