
DROP TABLE IF EXISTS BCH_TRANSACTIONDETAILS;

CREATE TABLE BCH_TRANSACTIONDETAILS
(
  TXID NVARCHAR(64) NOT NULL,
  ADDRESS NVARCHAR(64) NOT NULL,
  AMOUNT DECIMAL(16, 8),
  CATEGORY NVARCHAR(50),
  CREATETIME DATETIME DEFAULT CURRENT_TIMESTAMP()
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE BCH_TRANSACTIONDETAILS ADD PRIMARY KEY PK_BCH_TRANSACTIONDETAILS(TXID, ADDRESS);