DROP TABLE IF EXISTS BTC_BLOCKS;

CREATE TABLE BTC_BLOCKS
(
  HASH NVARCHAR(64) PRIMARY KEY NOT NULL,
  HEIGHT INT,
  STATE INT,
  CREATETIME DATETIME DEFAULT CURRENT_TIMESTAMP()
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE BTC_BLOCKS ADD UNIQUE UX_BTC_BLOCKS_HEIGHT(HEIGHT);