
DROP TABLE IF EXISTS BTC_SENDREQUESTS;

CREATE TABLE BTC_SENDREQUESTS
(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  OUTREQUESTNO NVARCHAR(50) NOT NULL,
  ADDRESS NVARCHAR(64) NOT NULL,
  AMOUNT DECIMAL(16, 8),
  STATE INT DEFAULT 0,
  CREATETIME DATETIME DEFAULT CURRENT_TIMESTAMP()
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE BTC_SENDREQUESTS ADD UNIQUE UX_BTC_SENDREQUESTS_OUTREQUESTNO(OUTREQUESTNO);
ALTER TABLE BTC_SENDREQUESTS ADD INDEX IX_BTC_SENDREQUESTS_ADDRESS(ADDRESS);
ALTER TABLE BTC_SENDREQUESTS ADD INDEX IX_BTC_SENDREQUESTS_CREATETIME(CREATETIME);
ALTER TABLE BTC_SENDREQUESTS ADD INDEX IX_BTC_SENDREQUESTS_STATE(STATE);