DROP TABLE IF EXISTS BTC_TRANSACTIONS;

CREATE TABLE BTC_TRANSACTIONS
(
  TXID NVARCHAR(64) PRIMARY KEY NOT NULL,
  BLOCKHASH NVARCHAR(64) NOT NULL,
  CONFIRMATIONS INT DEFAULT 0,
  STATE INT DEFAULT 0,
  CREATETIME DATETIME DEFAULT CURRENT_TIMESTAMP()
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE BTC_TRANSACTIONS ADD INDEX IX_BTC_TRANSACTIONS_BLOCKHASH(BLOCKHASH);
ALTER TABLE BTC_TRANSACTIONS ADD INDEX IX_BTC_TRANSACTIONS_STATE(STATE);