
DROP TABLE IF EXISTS BTC_TRANSACTIONDETAILS;

CREATE TABLE BTC_TRANSACTIONDETAILS
(
  TXID NVARCHAR(64) NOT NULL,
  ADDRESS NVARCHAR(64) NOT NULL,
  AMOUNT DECIMAL(16, 8),
  CATEGORY NVARCHAR(50),
  CREATETIME DATETIME DEFAULT CURRENT_TIMESTAMP()
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE BTC_TRANSACTIONDETAILS ADD PRIMARY KEY PK_BTC_TRANSACTIONDETAILS(TXID, ADDRESS);