
DROP TABLE IF EXISTS BTC_SENDTRANSACTIONDETAILS;

CREATE TABLE  BTC_SENDTRANSACTIONDETAILS
(
  TXID NVARCHAR(64),
  ADDRESS NVARCHAR(34),
  AMOUNT DECIMAL(16, 8)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE BTC_SENDTRANSACTIONDETAILS ADD PRIMARY KEY PK_BTC_SENDTRANSACTIONDETAILS(TXID, ADDRESS);