
DROP TABLE IF EXISTS DASH_SENDTRANSACTIONDETAILS;

CREATE TABLE DASH_SENDTRANSACTIONDETAILS
(
  TXID NVARCHAR(64),
  ADDRESS NVARCHAR(34),
  AMOUNT DECIMAL(16, 8)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE DASH_SENDTRANSACTIONDETAILS ADD PRIMARY KEY PK_DASH_SENDTRANSACTIONDETAILS(TXID, ADDRESS);