DROP TABLE IF EXISTS DASH_BLOCKS;

CREATE TABLE DASH_BLOCKS
(
  HASH NVARCHAR(64) PRIMARY KEY NOT NULL,
  HEIGHT INT,
  STATE INT,
  CREATETIME DATETIME DEFAULT CURRENT_TIMESTAMP()
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE DASH_BLOCKS ADD UNIQUE UX_DASH_BLOCKS_HEIGHT(HEIGHT);