
DROP TABLE IF EXISTS DASH_SENDREQUESTS;

CREATE TABLE DASH_SENDREQUESTS
(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  OUTREQUESTNO NVARCHAR(50) NOT NULL,
  ADDRESS NVARCHAR(64) NOT NULL,
  AMOUNT DECIMAL(16, 8),
  STATE INT DEFAULT 0,
  CREATETIME DATETIME DEFAULT CURRENT_TIMESTAMP()
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE DASH_SENDREQUESTS ADD UNIQUE UX_DASH_SENDREQUESTS_OUTREQUESTNO(OUTREQUESTNO);
ALTER TABLE DASH_SENDREQUESTS ADD INDEX IX_DASH_SENDREQUESTS_ADDRESS(ADDRESS);
ALTER TABLE DASH_SENDREQUESTS ADD INDEX IX_DASH_SENDREQUESTS_CREATETIME(CREATETIME);
ALTER TABLE DASH_SENDREQUESTS ADD INDEX IX_DASH_SENDREQUESTS_STATE(STATE);