DROP TABLE IF EXISTS ETH_RECEIVENOTIFYLOGS;

CREATE TABLE ETH_RECEIVENOTIFYLOGS
(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  TXID NVARCHAR(66) NOT NULL,
  ADDRESS NVARCHAR(45),
  AMOUNT DECIMAL(16, 8) DEFAULT 0,
  NOTIFIEDCOUNT INT DEFAULT 0,
  NOTIFYRESPONSETEXT TEXT,
  NEXTNOTIFYTIME DATETIME  DEFAULT CURRENT_TIMESTAMP(),
  CREATETIME DATETIME DEFAULT CURRENT_TIMESTAMP()
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE ETH_RECEIVENOTIFYLOGS ADD INDEX IX_ETH_RECEIVENOTIFYLOGS_NEXTNOTIFYTIME(NEXTNOTIFYTIME);
