DROP TABLE IF EXISTS ETH_TRANSACTIONS;

CREATE TABLE ETH_TRANSACTIONS
(
  TXID NVARCHAR(66) PRIMARY KEY NOT NULL,
  BLOCKHASH NVARCHAR(66) NOT NULL,
  CONFIRMATIONS INT DEFAULT 0,
  STATE INT DEFAULT 0,
  CREATETIME DATETIME DEFAULT CURRENT_TIMESTAMP()
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE ETH_TRANSACTIONS ADD INDEX IX_ETH_TRANSACTIONS_BLOCKHASH(BLOCKHASH);
ALTER TABLE ETH_TRANSACTIONS ADD INDEX IX_ETH_TRANSACTIONS_STATE(STATE);