DROP TABLE IF EXISTS ETH_BLOCKS;

CREATE TABLE ETH_BLOCKS
(
  HASH NVARCHAR(66) PRIMARY KEY NOT NULL,
  HEIGHT INT,
  STATE INT,
  CREATETIME DATETIME DEFAULT CURRENT_TIMESTAMP()
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE ETH_BLOCKS ADD UNIQUE UX_ETH_BLOCKS_HEIGHT(HEIGHT);