
DROP TABLE IF EXISTS ETH_SENDTRANSACTIONDETAILS;

CREATE TABLE ETH_SENDTRANSACTIONDETAILS
(
  TXID NVARCHAR(66),
  ADDRESS NVARCHAR(45),
  AMOUNT DECIMAL(16, 8)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE ETH_SENDTRANSACTIONDETAILS ADD PRIMARY KEY PK_ETH_SENDTRANSACTIONDETAILS(TXID, ADDRESS);