
DROP TABLE IF EXISTS LTC_SENDTRANSACTIONDETAILS;

CREATE TABLE  LTC_SENDTRANSACTIONDETAILS
(
  TXID NVARCHAR(64),
  ADDRESS NVARCHAR(34),
  AMOUNT DECIMAL(16, 8)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE LTC_SENDTRANSACTIONDETAILS ADD PRIMARY KEY PK_LTC_SENDTRANSACTIONDETAILS(TXID, ADDRESS);