DROP TABLE IF EXISTS LTC_BLOCKS;

CREATE TABLE LTC_BLOCKS
(
  HASH NVARCHAR(64) PRIMARY KEY NOT NULL,
  HEIGHT INT,
  STATE INT,
  CREATETIME DATETIME DEFAULT CURRENT_TIMESTAMP()
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE LTC_BLOCKS ADD UNIQUE UX_LTC_BLOCKS_HEIGHT(HEIGHT);