DROP TABLE IF EXISTS LTC_TRANSACTIONS;

CREATE TABLE LTC_TRANSACTIONS
(
  TXID NVARCHAR(64) PRIMARY KEY NOT NULL,
  BLOCKHASH NVARCHAR(64) NOT NULL,
  CONFIRMATIONS INT DEFAULT 0,
  STATE INT DEFAULT 0,
  CREATETIME DATETIME DEFAULT CURRENT_TIMESTAMP()
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE LTC_TRANSACTIONS ADD INDEX IX_LTC_TRANSACTIONS_BLOCKHASH(BLOCKHASH);
ALTER TABLE LTC_TRANSACTIONS ADD INDEX IX_LTC_TRANSACTIONS_STATE(STATE);