DROP TABLE IF EXISTS ZEC_TRANSACTIONS;

CREATE TABLE ZEC_TRANSACTIONS
(
  TXID NVARCHAR(64) PRIMARY KEY NOT NULL,
  BLOCKHASH NVARCHAR(64) NOT NULL,
  CONFIRMATIONS INT DEFAULT 0,
  STATE INT DEFAULT 0,
  CREATETIME DATETIME DEFAULT CURRENT_TIMESTAMP()
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE ZEC_TRANSACTIONS ADD INDEX IX_ZEC_TRANSACTIONS_BLOCKHASH(BLOCKHASH);
ALTER TABLE ZEC_TRANSACTIONS ADD INDEX IX_ZEC_TRANSACTIONS_STATE(STATE);