
DROP TABLE IF EXISTS ZEC_SENDTRANSACTIONDETAILS;

CREATE TABLE ZEC_SENDTRANSACTIONDETAILS
(
  TXID NVARCHAR(64),
  ADDRESS NVARCHAR(34),
  AMOUNT DECIMAL(16, 8)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE ZEC_SENDTRANSACTIONDETAILS ADD PRIMARY KEY PK_ZEC_SENDTRANSACTIONDETAILS(TXID, ADDRESS);