DROP TABLE IF EXISTS ZEC_BLOCKS;

CREATE TABLE ZEC_BLOCKS
(
  HASH NVARCHAR(64) PRIMARY KEY NOT NULL,
  HEIGHT INT,
  STATE INT,
  CREATETIME DATETIME DEFAULT CURRENT_TIMESTAMP()
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE ZEC_BLOCKS ADD UNIQUE UX_ZEC_BLOCKS_HEIGHT(HEIGHT);