
DROP TABLE IF EXISTS ZEC_SENDREQUESTS;

CREATE TABLE ZEC_SENDREQUESTS
(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  OUTREQUESTNO NVARCHAR(50) NOT NULL,
  ADDRESS NVARCHAR(64) NOT NULL,
  AMOUNT DECIMAL(16, 8),
  STATE INT DEFAULT 0,
  CREATETIME DATETIME DEFAULT CURRENT_TIMESTAMP()
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE ZEC_SENDREQUESTS ADD UNIQUE UX_ZEC_SENDREQUESTS_OUTREQUESTNO(OUTREQUESTNO);
ALTER TABLE ZEC_SENDREQUESTS ADD INDEX IX_ZEC_SENDREQUESTS_ADDRESS(ADDRESS);
ALTER TABLE ZEC_SENDREQUESTS ADD INDEX IX_ZEC_SENDREQUESTS_CREATETIME(CREATETIME);
ALTER TABLE ZEC_SENDREQUESTS ADD INDEX IX_ZEC_SENDREQUESTS_STATE(STATE);