
DROP TABLE IF EXISTS ZEC_TRANSACTIONDETAILS;

CREATE TABLE ZEC_TRANSACTIONDETAILS
(
  TXID NVARCHAR(64) NOT NULL,
  ADDRESS NVARCHAR(64) NOT NULL,
  AMOUNT DECIMAL(16, 8),
  CATEGORY NVARCHAR(50),
  CREATETIME DATETIME DEFAULT CURRENT_TIMESTAMP()
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE ZEC_TRANSACTIONDETAILS ADD PRIMARY KEY PK_ZEC_TRANSACTIONDETAILS(TXID, ADDRESS);